[package]
name = "StandardsValidator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "^4.5"
serde_json = "^1.0"

[dependencies.serde]
version = "^1.0"
features = ["derive"]

[dependencies.tes3]
git = "https://github.com/Greatness7/tes3"
default-features = false
features = ["esp"]
